_BASE_: "../Base-CenterNet.yaml"
MODEL:
  CENTERNET:
    ENCODER:
      NAME: 'V2_1.0x'
    DECODER:
      CHANNELS: [1024, 512, 256]
      DIM: 128
      CONV: 'deform_conv_square_depthwise'
    HEAD:
      DIM: 128
      CONV: 'deform_conv_square_depthwise'
    NUM_DET_MAX: 64
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  IMS_PER_BATCH: 128
  BASE_LR: 0.01
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 1000
TEST:
  DETECTIONS_PER_IMAGE: 64
